### ISSUE TITLE
open tif

### ISSUE THREAD

**Issue by cornerman54** [tesseract4java/tesseract4java#38] opened 2016-11-05 10:11 UTC
I installed the program without any failure messages And when I open the program and say file: new project and try to open a tif then I see a sandglass but the file doesn't open. What am I doing wrong
![image](https://cloud.githubusercontent.com/assets/23275584/20029285/90ae82e2-a348-11e6-99ad-1bf126327f54.png)

**Comment by pvorb** [comment] 2016-11-06 20:50
If it's possible, can you attach the TIFF files, so I can have a look at what might be wrong?

**Comment by cornerman54** [comment] 2016-11-07 05:13
I tried it on this file

 

 

PS But I think my settings aren’t right Can you help me with the settings and give a step by step description. I want to pay / donate for it, because its very impotant for me

 

 

 

Jannes Hoekman

Dioneth 

 

Van: Paul Vorbach [mailto:notifications@github.com] 
Verzonden: zondag 6 november 2016 21:51
Aan: tesseract4java/tesseract4java <tesseract4java@noreply.github.com>
CC: cornerman54 <webmaster@dioneth.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tesseract4java/tesseract4java] open tif (#38)

 

If it's possible, can you attach the TIFF files, so I can have a look at what might be wrong?

**Comment by cornerman54** [comment] 2016-11-07 09:00
It opens the files but they don't process
![0187](https://cloud.githubusercontent.com/assets/23275584/20051751/eef6a904-a4d0-11e6-897d-22ac4e26afb2.png)

**Comment by cornerman54** [comment] 2016-11-07 09:01
Van: Paul Vorbach [mailto:notifications@github.com] 
Verzonden: zondag 6 november 2016 21:51
Aan: tesseract4java/tesseract4java <tesseract4java@noreply.github.com>
CC: cornerman54 <webmaster@dioneth.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tesseract4java/tesseract4java] open tif (#38)

 

If it's possible, can you attach the TIFF files, so I can have a look at what might be wrong?

**Comment by cornerman54** [comment] 2016-11-07 16:31
![0001](https://cloud.githubusercontent.com/assets/23275584/20065871/feaf78be-a50f-11e6-88bf-5d31213871a0.png)

**Comment by cornerman54** [comment] 2016-11-07 18:23
Did you recieve my file?

 

 

 

Jannes Hoekman

Dioneth

 

Van: Paul Vorbach [mailto:notifications@github.com] 
Verzonden: zondag 6 november 2016 21:51
Aan: tesseract4java/tesseract4java <tesseract4java@noreply.github.com>
CC: cornerman54 <webmaster@dioneth.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tesseract4java/tesseract4java] open tif (#38)

 

If it's possible, can you attach the TIFF files, so I can have a look at what might be wrong?

**Comment by pvorb** [comment] 2016-11-07 19:58
Yes, I received your files. I have a full-time job and only work on this project in my spare time, so I'm usually not able to answer questions before 20:00 (Europe/Berlin).

I also edited and deleted some of your replies to make this thread more readable.

***

Regarding your question:

There really seems to be an issue with these images but I don't know where the problem is, yet. I'm currently debugging the application and will let you know once I find a solution.

**Comment by pvorb** [comment] 2016-11-07 20:25
The issue appears to be that the program does not handle the 32-bit BGR color model correctly. In order to make the images work, please convert them to 24-bit RGB, 8-bit Grayscale or 1-bit Monochrome.

If this does not help, I'll have another look.

**Comment by cornerman54** [comment] 2016-11-07 23:13
First I am sorry I didn’t know

 

But to my knoledge I scan with 24 color and not with 32! It open the picture but when I say preview then nothing happens. I also get a thumbnail but see nothing in de preprocessingmap

 

 

 



 

 

 

 

 

Van: Paul Vorbach [mailto:notifications@github.com] 
Verzonden: maandag 7 november 2016 21:25
Aan: tesseract4java/tesseract4java <tesseract4java@noreply.github.com>
CC: cornerman54 <webmaster@dioneth.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [tesseract4java/tesseract4java] open tif (#38)

 

The issue appears to be that the program does not handle the 32-bit BGR color model correctly. In order to make the images work, please convert them to 24-bit RGB, 8-bit Grayscale or 1-bit Monochrome.

If this does not help, I'll have another look.

**Comment by pvorb** [comment] 2020-10-17 21:06
I'm not sure, but this could be fixed by #51. Can you re-check? You need to build the application yourself to test it.

**Closed** 2021-07-30 23:56 UTC
